import LibraryProvider from "@/app/context/Library";
import Dayjs from "@/app/context/Dayjs";
import ReactQuery from "@/app/context/ReactQuery";
import { robotoFont } from "@/app/theme/fontFamily";
import "@/app/globals.scss";

type LayoutProps = {
  children: React.ReactNode;
};
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps) {
  //for access to locale inside layout we get it inside 'params' prop
  return (
    <html>
      <body className={`bg-background-main ${robotoFont.className} `}>
        <LibraryProvider>
          <Dayjs>
            <ReactQuery>
              <main>{children}</main>
            </ReactQuery>
          </Dayjs>
        </LibraryProvider>
        <div id="portals"></div>
      </body>
    </html>
  );
}
